export const projects = [
  {
    title: 'Bate-Papo',
    description: "Este projeto foi desenvolvido usando React.js, Redux e Firebase",
      image: '/images/1.png',
    source: 'https://bate-papo-814de.firebaseapp.com/',
    visit: 'https://github.com/dimasneto7/bate-papo',
    id: 0,
  },  
  {
    title: 'Podcastr',
    description:"Este projeto foi desenvolvido usando React.js e Next.js e Sass",
    image: '/images/2.png',
    source: 'https://podcastr-dimasneto7.vercel.app/',
    visit: 'https://github.com/dimasneto7/podcastrnext',
    id: 1,
  },
  {
    title: 'Move.it',
    description: "Este projeto foi desenvolvido usando React.js, Next,js e Typescript",
    image: '/images/3.png',
    source: 'https://moveit-dimasneto7.vercel.app/',
    visit: 'https://github.com/dimasneto7/moveit',
    id: 2,  
  },
  {
    title: 'Dt Money',
    description: "Ferramentas: React.js, Typescript, Styled Component e Mirage JS",
    image: '/images/4.png',
    source: 'https://mymoney-git-main-dimasneto7.vercel.app/',
    visit: 'https://github.com/dimasneto7/mymoney',
    id: 3,  
  },
  {
    title: 'dashgo',
    description: "Desenvolvido usando React.js, Next.js, Typescritp e Chakra UI",
    image: '/images/5.png',
    source: 'https://dashgo-sigma.vercel.app/',
    visit: 'https://github.com/dimasneto7/dashgo',
    id: 4,  
  },
  {
    title: 'Dimas Neto',
    description: "Desenvolvido usando HTML, CSS e Javascript",
    image: '/images/6.png',
    source: 'https://portfolio-dimasneto7.vercel.app/',
    visit: 'https://github.com/dimasneto7/portfolio',
    id: 5,  
  },
];
